name: Generate Datas

on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão necessária para salvar o arquivo na branch output
    steps:
      # Gera a animação da cobrinha
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Yuzu13
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-dark
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Pega os arquivos gerados e envia para a branch 'output'
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
